FROM php:8.2-cli

# Instalar dependencias del sistema
RUN apt-get update && apt-get install -y \
    git curl zip unzip libpng-dev libonig-dev libxml2-dev libzip-dev \
    libjpeg-dev libfreetype6-dev libicu-dev \
    && rm -rf /var/lib/apt/lists/*

# Extensión Redis
RUN pecl install redis && docker-php-ext-enable redis

# Extensiones PHP
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install pdo pdo_mysql mbstring exif pcntl bcmath gd zip intl

# Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Directorio de trabajo
WORKDIR /var/www/html

# Copiar proyecto
COPY . .

# Permisos necesarios
RUN chmod -R 775 storage bootstrap/cache

# Puerto que Railway usa
EXPOSE 8080

# Servidor Laravel escuchando el puerto correcto
CMD php artisan serve --host=0.0.0.0 --port=${PORT}
