FROM php:8.2.12-fpm
# Instalar extensiones de PHP necesarias
RUN apt-get update && apt-get install -y \
    git curl zip unzip libpng-dev libonig-dev libxml2-dev libzip-dev \
    libjpeg-dev libfreetype6-dev \
    && rm -rf /var/lib/apt/lists/*
#todo lo escrito anterior, significa que se instalan las dependencias necesarias para que php funcione correctamente
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install pdo mbstring exif pcntl bcmath gd zip
#copiamos el composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
# Establecer el directorio de trabajo
WORKDIR /var/www/html
# EXPONER EL PUERTO 9000
EXPOSE 9000
# Comando para iniciar PHP-FPM
CMD ["php-fpm"]
